# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

locale: "en-US"
title: def brian(automate)
subtitle: Covering topics relating to networking and automation!
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Covering topics relating to networking and automation!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.yaklin.ca" # the base hostname & protocol for your site, e.g. http://example.com

repository: "brianyaklin/brianyaklin.github.io"

# Theme settings
minimal_mistakes_skin: "air" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
teaser: /assets/images/hal-gatewood-8MBd4rAgJ-c-unsplash_small.jpg
logo: /assets/images/android-chrome-192x192.png
search: true
og_image: /assets/images/hal-gatewood-8MBd4rAgJ-c-unsplash_small.jpg
tag_archive:
  type: liquid
  path: /tags/
atom_feed:
  hide: true

# Social sharing
twitter_username: byaklin6
github_username: brianyaklin
linkedin_username: brian-yaklin-6420173a
social:
  name: Brian Yaklin
  links:
    - https://twitter.com/byaklin6
    - https://www.linkedin.com/in/brian-yaklin-6420173a
    - https://github.com/brianyaklin

# Site author
author:
  name: "Brian Yaklin"
  location: "Calgary, AB"
  avatar: "/assets/images/author-avatar.jpeg"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/brianyaklin"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/brian-yaklin-6420173a"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/byaklin6"
    - label: "Networking Tools"
      icon: "fas fa-fw fa-toolbox"
      url: "https://tools.yaklin.ca"

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Conversion
markdown: kramdown
highlighter: rouge

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Outputting
output_ext: .html
permalink: /:year/:month/:day/:title:output_ext
paginate: 10
paginate_path: /page:num/
timezone: Canada/Mountain # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
      show_date: true
      toc: true
      toc_sticky: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true