site_name: Yaklin.ca
site_description: Covering topics relating to networking and automation!
site_url: https://www.yaklin.com
repo_url: https://github.com/brianyaklin

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.indexes
    - navigation.footer
    - navigation.tracking
    - search.suggest
    - search.highlight
    - search.share
    - toc.follow
    - content.code.copy
    - content.tabs.link
  palette:
    scheme: slate
  icon:
    logo: fontawesome/solid/route

plugins:
  - search
  - meta
  - tags
  - blog:
      blog_dir: .

nav:
  - Home: index.md

extra:
  generator: false
  analytics:
    provider: google
    property: G-Q1WGH30J2R
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

copyright: >
  Copyright &copy; 2025 Yaklin.ca –
  <a href="#__consent">Change cookie settings</a>

markdown_extensions:
  - toc:
      permalink: true
      title: On this page
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
